[package]
name = "playstuntsdx"
version = "0.1.0"
description = "Windows desktop build of PlayStunts DX"
authors = ["Endprodukt"]
edition = "2021"

[lib]
name = "playstuntsdx_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }
cc = "1"

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
