export type ForceFeedbackSurface = 'road' | 'grass' | 'air';

export type ForceFeedbackTelemetry = {
  speed: number;
  roadSpeed: number;
  steeringAngle: number;
  wheelAngle: number;
  frontWheelAngle: number;
  slip: number;
  spin: number;
  sliding: number;
  surfaces: number[];
  allContact: number;
  updatedAt: number;
};

const clamp = (value: number, min: number, max: number) => Math.max(min, Math.min(max, value));

let telemetry: ForceFeedbackTelemetry | null = null;
let grassPhase = 0;
let impactPulseStrength = 0;
let impactPulseStartedAt = 0;
let menuPulseStartedAt = 0;

export function updateForceFeedbackTelemetry(next: Omit<ForceFeedbackTelemetry, 'updatedAt'>) {
  telemetry = { ...next, surfaces: [...next.surfaces], updatedAt: Date.now() };
}

/**
 * Replaces only the wheel-contact part of the latest player sample after the
 * real track-contact pass. This keeps transient grip/slip data from stepGrip,
 * while surface rumble uses the wheel surfaces produced by the same physics tick.
 */
export function updateForceFeedbackContact(
  surfaces: number[],
  allContact: number,
  impactSpeed = 0,
) {
  if (!telemetry) return;
  const now = Date.now();
  telemetry = {
    ...telemetry,
    surfaces: [...surfaces],
    allContact,
    updatedAt: now,
  };

  // The original physics sets its landing-impact flag only above fallSpeed 190.
  // Scale that real impact velocity into a short wheel kick instead of adding a
  // generic road-bump effect.
  if (impactSpeed > 190) {
    impactPulseStrength = clamp(0.28 + (impactSpeed - 190) / 650, 0.28, 0.9);
    impactPulseStartedAt = now;
  }
}

export function triggerForceFeedbackMenuPulse() {
  menuPulseStartedAt = Date.now();
}

export function clearForceFeedbackTelemetry() {
  telemetry = null;
  grassPhase = 0;
  impactPulseStrength = 0;
  impactPulseStartedAt = 0;
}

export function sampleForceFeedback(physicalSteering: number) {
  const now = Date.now();
  const menuAge = now - menuPulseStartedAt;
  const menuForce =
    menuPulseStartedAt > 0 && menuAge >= 0 && menuAge < 80
      ? Math.sin((menuAge / 80) * Math.PI * 2) * (1 - menuAge / 80) * 0.18
      : 0;

  if (!telemetry || now - telemetry.updatedAt > 250) {
    return menuForce;
  }

  const contactCount = telemetry.surfaces.filter((surface) => surface !== 0).length;
  // Surface id 4 is the real Stunts grass/off-road contact. Road deliberately
  // receives no artificial continuous vibration.
  const grassCount = telemetry.surfaces.filter((surface) => surface === 4).length;
  const contactScale = contactCount / 4;
  const speedScale = clamp(Math.abs(telemetry.speed) / 1800, 0, 1);
  const roadSpeedScale = clamp(Math.abs(telemetry.roadSpeed) / 650, 0, 1);
  const wheelSteering =
    Math.abs(physicalSteering) > 0.02
      ? physicalSteering
      : clamp(telemetry.wheelAngle / 1024, -1, 1);
  const gripLoad = contactScale * (0.15 + 0.85 * speedScale);

  // Constant-force self-aligning torque: the steering input supplies direction,
  // while actual contact and vehicle speed determine how much load the wheel has.
  const centering =
    wheelSteering *
    gripLoad *
    (0.95 + 1.35 * roadSpeedScale);

  // Counter-steer during a slide comes from the signed slip/spin generated by
  // the original grip step, not from visual yaw or an invented drift state.
  const slideAmount = clamp(telemetry.sliding / 28, 0, 1) * contactScale;
  const signedSlip = clamp(telemetry.slip / 100, -1, 1);
  const signedSpin = clamp(telemetry.spin / 1200, -1, 1);
  const slideAligning =
    clamp(-signedSlip * 1.15 + signedSpin * 0.38, -1.3, 1.3) *
    Math.max(slideAmount, Math.abs(signedSlip) * 0.65) *
    (0.3 + 0.7 * speedScale);

  let grassForce = 0;
  if (grassCount > 0) {
    const frequency = 10 + 34 * roadSpeedScale;
    grassPhase = (grassPhase + (frequency / 66) * Math.PI * 2) % (Math.PI * 2);
    const grassScale = grassCount / 4;
    grassForce =
      Math.sin(grassPhase) *
      grassScale *
      (0.28 + 0.88 * roadSpeedScale);
  } else {
    grassPhase = 0;
  }

  const impactAge = now - impactPulseStartedAt;
  const impactForce =
    impactPulseStartedAt > 0 && impactAge >= 0 && impactAge < 120
      ? Math.sin((impactAge / 120) * Math.PI * 2) *
        (1 - impactAge / 120) *
        impactPulseStrength
      : 0;

  if (telemetry.allContact === 0 && contactCount === 0) {
    return menuForce;
  }

  return clamp(centering + slideAligning + grassForce + impactForce + menuForce, -1, 1);
}
